theme: minima
title: Home Language Insights with dbt and BigQuery
description: Diving further into Home Language characteristics by CMA with Looker Studio charts using BigQuery and dbt.
author: 
  name: Ian Mosley
  email: iamosley@fastmail.com
minima:
  header_pages:
    - about.html
